version: '3.1'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: soundarya
      MYSQL_USER: soundarya1
      MYSQL_PASSWORD: soundarya123
      MYSQL_RANDOM_ROOT_PASSWORD: '1'  # Corrected environment variable name
    volumes:
      - db:/var/lib/mysql
    expose:
      - 3306
      - 33060

  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: soundarya1
      WORDPRESS_DB_PASSWORD: soundarya123
      WORDPRESS_DB_NAME: soundarya
    volumes:
      - wordpress:/var/www/html

volumes:
  db:
  wordpress:

